06-22 17:20:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "GDAREFERENCE" nicht gefunden
Table "GDAREFERENCE" not found; SQL statement:
DROP TABLE GDAREFERENCE [42102-172]
06-22 17:20:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequenz "ID_GDAREFERENCE_SEQ" nicht gefunden
Sequence "ID_GDAREFERENCE_SEQ" not found; SQL statement:
DROP SEQUENCE ID_GDAREFERENCE_SEQ [90036-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-22 17:23:33 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "Alexander" nicht gefunden
Column "Alexander" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, "Alexander", "Gruber", "Addresse1", "123", "a@g.net", "firma1", 

"password1") [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:237)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-22 17:28:04 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Stefan', 'Goetzinger', 'Addresse2', '1234', 's@g.net', 

'firma2', 'password2')
INSERT[*] INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Daniel', 'Puchner', 'Addresse3', '12345', 'd@p.net', 'firma3', 
'password3')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Alexander', 'Kiennast', 'Addresse4', '123456', 'a@k.net', 

'firma4', 'password4')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Philipp', 'Schnatter', 'Addresse5', '1234567', 'p@s.net', 

'firma5', 'password5') "
Syntax error in SQL statement "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Stefan', 'Goetzinger', 'Addresse2', '1234', 's@g.net', 

'firma2', 'password2')
INSERT[*] INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Daniel', 'Puchner', 'Addresse3', '12345', 'd@p.net', 'firma3', 
'password3')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Alexander', 'Kiennast', 'Addresse4', '123456', 'a@k.net', 

'firma4', 'password4')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Philipp', 'Schnatter', 'Addresse5', '1234567', 'p@s.net', 

'firma5', 'password5') "; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Stefan', 'Goetzinger', 'Addresse2', '1234', 's@g.net', 

'firma2', 'password2')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Daniel', 'Puchner', 'Addresse3', '12345', 'd@p.net', 'firma3', 
'password3')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Alexander', 'Kiennast', 'Addresse4', '123456', 'a@k.net', 

'firma4', 'password4')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Philipp', 'Schnatter', 'Addresse5', '1234567', 'p@s.net', 

'firma5', 'password5') [42000-172]
06-22 17:28:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Stefan', 'Goetzinger', 'Addresse2', '1234', 's@g.net', 

'firma2', 'password2')
INSERT[*] INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Daniel', 'Puchner', 'Addresse3', '12345', 'd@p.net', 'firma3', 
'password3')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Alexander', 'Kiennast', 'Addresse4', '123456', 'a@k.net', 

'firma4', 'password4')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Philipp', 'Schnatter', 'Addresse5', '1234567', 'p@s.net', 

'firma5', 'password5') "
Syntax error in SQL statement "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Stefan', 'Goetzinger', 'Addresse2', '1234', 's@g.net', 

'firma2', 'password2')
INSERT[*] INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Daniel', 'Puchner', 'Addresse3', '12345', 'd@p.net', 'firma3', 
'password3')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Alexander', 'Kiennast', 'Addresse4', '123456', 'a@k.net', 

'firma4', 'password4')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.NEXTVAL, 'Philipp', 'Schnatter', 'Addresse5', '1234567', 'p@s.net', 

'firma5', 'password5') "; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Stefan', 'Goetzinger', 'Addresse2', '1234', 's@g.net', 

'firma2', 'password2')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Daniel', 'Puchner', 'Addresse3', '12345', 'd@p.net', 'firma3', 
'password3')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Alexander', 'Kiennast', 'Addresse4', '123456', 'a@k.net', 

'firma4', 'password4')
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.nextval, 'Philipp', 'Schnatter', 'Addresse5', '1234567', 'p@s.net', 

'firma5', 'password5') [42000-172]
06-22 18:08:00 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 1, 1, 'Es werde Guglhupf', '2014-01-01', '2013-06-01', '2014-31-12', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-22 18:09:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Kann "DATE" "2014-31-12" nicht umwandeln
Cannot parse "DATE" constant "2014-31-12"; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 1, 1, 'Es werde Guglhupf', '2014-01-01', '2013-06-01', '2014-31-12', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0) -- ((NEXT VALUE FOR PUBLIC.ID_PRODUCT_SEQ), 1, 1, 'Es werde Guglhupf', '2014-01-01', '2013-06-01', '2014-31-12', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0) [22007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:158)
	at org.h2.value.ValueDate.parse(ValueDate.java:70)
	at org.h2.value.Value.convertTo(Value.java:819)
	at org.h2.table.Column.convert(Column.java:145)
	at org.h2.command.dml.Insert.insertRows(Insert.java:114)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2014-31-12
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:276)
	at org.h2.value.ValueDate.parse(ValueDate.java:68)
	... 15 more
06-24 19:06:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 1, 1, 'Es werde Guglhupf', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:06:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 2, 2, 'Wiener Schnitzel', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Foods', 'LKW Augustin', 1500.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:06:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 3, 3, 'sachertorte Extended', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:06:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 4, 4, 'Overkrapfen', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:06:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 5, 5, 'Max Stramm', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Deep fried Food', 'LKW Augustin', 1000.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:06:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 6, 1, 'Mojito', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Drinks Linz', 'LKW Augustin', 500.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:06:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "PRODUCT_NAME" nicht gefunden
Column "PRODUCT_NAME" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCT_NAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST 

) VALUES (ID_PRODUCT_SEQ.nextval, 6, 1, 'Mojito2', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Drinks Linz', 'LKW Augustin', 2000.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 1, 25.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 2, 200.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 3, 100.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 4, 200.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 5, 125.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 6, 25.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 7, 125.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:07:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "REICPE_ID" nicht gefunden
Column "REICPE_ID" not found; SQL statement:
INSERT INTO INGREDIENT2RECIPE (ID, REICPE_ID, INGREDIENT_ID , AMOUNT ) VALUES (ID_INGREDIENT2RECIPE_SEQ.nextval, 1, 8, 250.0) [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 19:41:27 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.deleteRecipe(RecipeDAO.java:195)
	at bakewell.db.RecipeDAOTest.testRecipeDAODelete_ShouldWork(RecipeDAOTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 33 more
06-24 19:42:00 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.UpdateRecipe(RecipeDAO.java:352)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.deleteRecipe(RecipeDAO.java:195)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 33 more
06-24 21:01:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "COMMENT" nicht gefunden
Column "COMMENT" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCTNAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST, 

COMMENT ) VALUES (ID_PRODUCT_SEQ.nextval, 1, 1, 'Es werde Guglhupf', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0, 'no comment') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 21:01:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "COMMENT" nicht gefunden
Column "COMMENT" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCTNAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST, 

COMMENT ) VALUES (ID_PRODUCT_SEQ.nextval, 2, 2, 'Wiener Schnitzel', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Foods', 'LKW Augustin', 1500.0, 'no comment') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 21:01:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "COMMENT" nicht gefunden
Column "COMMENT" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCTNAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST, 

COMMENT ) VALUES (ID_PRODUCT_SEQ.nextval, 3, 3, 'sachertorte Extended', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0, 'no comment') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 21:01:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "COMMENT" nicht gefunden
Column "COMMENT" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCTNAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST, 

COMMENT ) VALUES (ID_PRODUCT_SEQ.nextval, 4, 4, 'Overkrapfen', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Bakery', 'LKW Augustin', 1000.0, 'no comment') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 21:01:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "COMMENT" nicht gefunden
Column "COMMENT" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCTNAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST, 

COMMENT ) VALUES (ID_PRODUCT_SEQ.nextval, 5, 5, 'Max Stramm', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Vienna Deep fried Food', 'LKW Augustin', 1000.0, 'no comment') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 21:01:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "COMMENT" nicht gefunden
Column "COMMENT" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCTNAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST, 

COMMENT ) VALUES (ID_PRODUCT_SEQ.nextval, 6, 1, 'Mojito', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Drinks Linz', 'LKW Augustin', 500.0, 'no comment') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 21:01:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "COMMENT" nicht gefunden
Column "COMMENT" not found; SQL statement:
INSERT INTO PRODUCT (ID, RECIPE_ID, CUSTOMER_ID , PRODUCTNAME , DELIVERYDATE , PRODUCTION_START , PRODUCTION_END , PRODUCTION_FACILITY, PRODUCTION_CONTRACTOR, TRANSPORT_CONTRACTOR, TRANSPORT_COST, 

COMMENT ) VALUES (ID_PRODUCT_SEQ.nextval, 6, 1, 'Mojito2', '2014-01-01', '2013-06-01', '2014-12-31', 'Wien', 'Drinks Linz', 'LKW Augustin', 2000.0, 'no comment') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-24 22:01:00 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:35)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-24 22:01:03 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.ProductDAO.openConnection(ProductDAO.java:78)
	at bakewell.db.ProductDAO.deleteProduct(ProductDAO.java:229)
	at bakewell.db.ProductDAOTest.testProductDAODelete_ShouldFail(ProductDAOTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:35)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-24 22:01:07 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:35)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-24 22:01:07 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.ProductDAO.openConnection(ProductDAO.java:78)
	at bakewell.db.ProductDAO.deleteProduct(ProductDAO.java:229)
	at bakewell.db.ProductDAOTest.testProductDAOSelect_ShouldWork(ProductDAOTest.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:35)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-24 22:01:08 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.ProductDAO.openConnection(ProductDAO.java:78)
	at bakewell.db.ProductDAO.deleteProduct(ProductDAO.java:229)
	at bakewell.db.ProductDAOTest.testProductDAOSelect_ShouldFail(ProductDAOTest.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:35)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-24 22:01:13 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.ProductDAO.openConnection(ProductDAO.java:78)
	at bakewell.db.ProductDAO.UpdateProduct(ProductDAO.java:382)
	at bakewell.db.ProductDAOTest.testProductDAOUpdate_ShouldWork(ProductDAOTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:35)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-25 11:27:34 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 32 more
06-25 11:28:50 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.UpdateRecipe(RecipeDAO.java:352)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:341)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 32 more
06-25 16:22:06 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 32 more
06-25 16:22:47 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.UpdateRecipe(RecipeDAO.java:351)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 32 more
06-25 16:46:31 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 32 more
06-25 16:47:03 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.UpdateRecipe(RecipeDAO.java:351)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 32 more
06-25 19:03:39 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.Ingredient2RecipeDAOTest.setUp(Ingredient2RecipeDAOTest.java:32)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-25 19:08:46 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:209)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.Ingredient2RecipeDAOTest.setUp(Ingredient2RecipeDAOTest.java:32)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-25 20:23:31 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:208)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 32 more
06-25 20:48:43 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:208)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:41)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 28 more
06-26 21:47:47 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.insertIngredient2Recipe(Ingredient2RecipeDAO.java:105)
	at bakewell.db.IngredientDAO.insertIngredient2RecipeNonPersistent(IngredientDAO.java:159)
	at bakewell.db.IngredientDAOTest.testIngredientDAOinsertIngredient2RecipeNonPersistent_ShouldWork(IngredientDAOTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 34 more
06-26 21:48:29 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.IngredientDAO.openConnection(IngredientDAO.java:74)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:407)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldFail(IngredientDAOTest.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:208)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.RecipeDAO.insertNewRecipe(RecipeDAO.java:114)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsertNewRecipe_ShouldWork(RecipeDAOTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 36 more
06-26 21:49:11 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:138)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:208)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 34 more
06-26 21:50:51 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.GDAReferenceDAO.openConnection(GDAReferenceDAO.java:70)
	at bakewell.db.GDAReferenceDAO.UpdateGDAReference(GDAReferenceDAO.java:259)
	at bakewell.db.GDAReferenceDAOTest.testGDAReferenceDAOUpdate_ShouldFail(GDAReferenceDAOTest.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:208)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:340)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:174)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:41)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 30 more
06-26 22:43:29 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:339)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:173)
	at bakewell.db.RecipeDAO.insertNewRecipe(RecipeDAO.java:114)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsertNewRecipe_ShouldWork(RecipeDAOTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 36 more
06-26 22:43:36 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:339)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:173)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldWork(RecipeDAOTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 35 more
06-26 22:43:43 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:138)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:339)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 34 more
06-26 22:46:38 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.insertIngredient2Recipe(Ingredient2RecipeDAO.java:105)
	at bakewell.db.IngredientDAO.insertIngredient2RecipeNonPersistent(IngredientDAO.java:159)
	at bakewell.db.IngredientDAOTest.testIngredientDAOinsertIngredient2RecipeNonPersistent_ShouldWork(IngredientDAOTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 34 more
06-26 22:46:43 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:138)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:337)
	at bakewell.db.RecipeDAOTest.testRecipeDAOInsert_ShouldFail(RecipeDAOTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 34 more
06-26 22:46:47 jdbc[2]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:337)
	at bakewell.db.RecipeDAO.deleteRecipe(RecipeDAO.java:194)
	at bakewell.db.RecipeDAOTest.testRecipeDAODelete_ShouldWork(RecipeDAOTest.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 35 more
06-26 22:47:20 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.RecipeDAO.openConnection(RecipeDAO.java:74)
	at bakewell.db.RecipeDAO.UpdateRecipe(RecipeDAO.java:347)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:337)
	at bakewell.db.RecipeDAOTest.testRecipeDAOUpdate_ShouldFail(RecipeDAOTest.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 34 more
06-26 22:47:36 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.GDAReferenceDAO.openConnection(GDAReferenceDAO.java:70)
	at bakewell.db.GDAReferenceDAO.insertGDAReference(GDAReferenceDAO.java:105)
	at bakewell.db.GDAReferenceDAOTest.testGDAReferenceDAOInsert_ShouldFail(GDAReferenceDAOTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:337)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:173)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:41)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 30 more
06-26 22:47:36 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.GDAReferenceDAO.openConnection(GDAReferenceDAO.java:70)
	at bakewell.db.GDAReferenceDAO.UpdateGDAReference(GDAReferenceDAO.java:256)
	at bakewell.db.GDAReferenceDAOTest.testGDAReferenceDAOUpdate_ShouldFail(GDAReferenceDAOTest.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:337)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:173)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:41)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 30 more
06-26 22:48:39 jdbc[2]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.ProductDAO.openConnection(ProductDAO.java:82)
	at bakewell.db.ProductDAO.UpdateProduct(ProductDAO.java:384)
	at bakewell.db.ProductDAOTest.testProductDAOUpdate_ShouldFail(ProductDAOTest.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.Ingredient2RecipeDAO.openConnection(Ingredient2RecipeDAO.java:70)
	at bakewell.db.Ingredient2RecipeDAO.selectIngredient2Recipe(Ingredient2RecipeDAO.java:205)
	at bakewell.db.RecipeDAO.selectRecipe(RecipeDAO.java:337)
	at bakewell.db.RecipeDAO.insertRecipe(RecipeDAO.java:173)
	at bakewell.db.ProductDAOTest.setUp(ProductDAOTest.java:41)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 30 more
